# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49fa87f8ac3d621f2de6c5e543bfba26941dc1b52ff9ea1e80f20e6ae5e451307b52046379e5e06665db4a65bcef43acc2f7db37c3a55e87049c1e363fdf30e3

test:
  secret_key_base: 2591a775a25a14ea4c60f65a0611ded960a0b9df36996ceb338b7297e540c26d8181233d88271bf142b4e178376ac7c23444481036cf328494c82d778816ac17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
