# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05fb0e5234a959712259ea50020e6c71d534809f49fcad98ef223cb9d4bebf6dff0245ef638d2786e3e6d5b17e192d66767393c06fbe0eb218d4097d3b8e9ecc

test:
  secret_key_base: 1de9bf61d0a3b1f4d9f4f7b2356c0ca4f0e55020fb9bf56668e4c8fac6d7ea77e1949a6a1531c1c20d9b5ccab7c2c4d58e6f6e1c60249cc8efd27a455e5caa3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
